name = "svc-radityoardi-worker"
main = "src/index.ts"
compatibility_date = "2026-09-09"
type = "modules"

# Replace the placeholders below with your Cloudflare account/zone IDs
account_id = "5c6ecb10e4803339aec471966b866236"
workers_dev = false

[build]
command = "npm run build"
